export default {
  DRAFT_FOR_USER: 'DRAFT_FOR_USER',
  DRAFT_PICK: 'DRAFT_PICK',
  DRAFT_PICK_HIGHEST_PRI: 'DRAFT_PICK_HIGHEST_PRI',
  DRAFT_UPDATE: 'DRAFT_UPDATE',
  RESET_PENDING_PICK_LIST: 'RESET_PENDING_PICK_LIST',
  SAVE_PICK_LIST: 'SAVE_PICK_LIST',
  SET_PICK_LIST: 'SET_PICK_LIST',
  STOP_DRAFT_FOR_USER: 'STOP_DRAFT_FOR_USER',
  UPDATE_PENDING_PICK_LIST: 'UPDATE_PENDING_PICK_LIST',
};
