export default {
  CURRENT_USER_CHANGE: 'CURRENT_USER_CHANGE',
  CURRENT_USER_CHANGE_SYNCED: 'CURRENT_USER_CHANGE_SYNCED',
  SET_ACTIVE_USERS: 'SET_ACTIVE_USERS',
  SET_APP_STATE: 'SET_APP_STATE',
  SET_GOLFERS: 'SET_GOLFERS',
  SET_IS_ADMIN: 'SET_IS_ADMIN',
  SET_CURRENT_TOURNEY: 'SET_CURRENT_TOURNEY',
  SET_USERS: 'SET_USERS',
  SET_ALL_TOURNEYS: 'SET_ALL_TOURNEYS',
  SET_ACTIVE_TOURNEY_ID: 'SET_ACTIVE_TOURNEY_ID',
  SET_PICKLIST_USERS: 'SET_PICKLIST_USERS',
};
